### ISSUE TITLE
Projets manquants

### ISSUE THREAD

**Issue by bernard-ng** [Jonathanmkg/Php-training#2]
Il manque le projet des heures supplémentaires et celui de la programmation orienté objet ! 

Pour la calculatrice il faut afficher le résultat en dessus du formulaire

**Comment by Jonathanmkg** [comment]
Merci . I'm still working on it we had electricity problem

**Comment by Jonathanmkg** [comment]
Merci, I'm still working on it 🙏🏾

**Comment by Jonathanmkg** [comment]
C'est sur l'ordinateur de itotafrica j'avais pas totalement finis je suis
bloqué à la partie html. Je vais voir comment passé et push c'est j'ai pu
faire
